import _         from 'lodash';
import Joi       from 'joi';
import Sequelize from 'sequelize';

import map from './map';

export default function sequelizeToJoi(model, {
    omitAssociations = false,
    omitAutoGenerated = false
} = {}) {
    // Ensure that the model we receive is a Sequelize Model
    if (!(model instanceof Sequelize.Model)) {
        throw new TypeError('model is not an instance of Sequelize.Model');
    }

    // The validator for the Sequelize model
    let joi = Joi.object();

    // Figure out what attributes we are mapping to create the validation schema
    let attributes = model.attributes;

    if (omitAutoGenerated) {
        attributes = _.omitBy(attributes, '_autoGenerated');
    }

    // The keys we parsed out of the model
    let keys = _.mapValues(attributes, map);

    if (!omitAssociations) {
        _.each(model.associations, (reference, name) => {
            // Only go one level deep to avoid circular references
            let schema = sequelizeToJoi(reference.target, { omitAssociations: true, omitAutoGenerated });

            if (reference.isSingleAssociation) {
                keys[name] = schema;
            } else {
                keys[name] = Joi.array().items(schema);
            }
        });
    }

    return joi.keys(keys);
}
