import _         from 'lodash';
import Joi       from 'joi';
import Sequelize from 'sequelize';

import map from './map';

export default function sequelizeToJoi(model, {
    omitAutoGenerated = false
} = {}) {
    // Ensure that the model we receive is a Sequelize Model
    if (!(model instanceof Sequelize.Model)) {
        throw new TypeError('model is not an instance of Sequelize.Model');
    }

    // The validator for the Sequelize model
    let joi = Joi.object();

    // Figure out what attributes we are mapping to create the validation schema
    let attributes = model.attributes;
    if (omitAutoGenerated) {
        attributes = _.omit(attributes, '_autoGenerated');
    }

    // The keys we parsed out of the model
    let keys = _.mapValues(attributes, map);

    return joi.keys(keys);
}
